# .github/workflows/android.yml
name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk python3-pip python3-venv \
          python3-dev libffi-dev libssl-dev libsqlite3-dev \
          libjpeg-dev zlib1g-dev build-essential autoconf automake libtool pkg-config \
          libncurses5-dev libncursesw5-dev libreadline-dev libbz2-dev liblzma-dev
        # Cython untuk p4a
        pip install cython

    - name: Install Buildozer & p4a
      run: |
        pip install --upgrade buildozer
        # (opsional) cache direktori ~/.local/share/python-for-android

    - name: Build APK
      run: |
        buildozer --verbose android debug

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: APK v1.0.${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/android/debug/*.apk
